### ISSUE TITLE
> conda install -y cmake, gcc=9.4.0, gxx, gcc_linux-64, gxx_linux-64, ninja -c conda-forge

### ISSUE THREAD

**Issue by Hyun-Myung** [IntelLabs/open-omics-alphafold#1]
Hi,
above command returned an error!
"
CondaValueError: invalid package specification: gcc=9.4.0,
"
I tried "conda update conda" ---> Didn't work!

==============>> I made it by doing one by one!

**Comment by sanchit-misra** [comment]
Could you please try the docker instructions? They might be easier. You can find them here: https://github.com/IntelLabs/Open-Omics-Acceleration-Framework/tree/main/pipelines/alphafold2

Regarding the specific error above: if you already have cmake and gcc > v9.4.0, you don't need to use conda to install it.

**Comment by narendrachaudhary51** [comment]
We have updated our installation instructions. Now conda environment can be created using a .yml file.

**Comment by narendrachaudhary51** [comment]
This issue has been resolved
