### ISSUE TITLE
where is subnets_multimer?

### ISSUE THREAD

**Issue by Lix1993** [IntelLabs/open-omics-alphafold#10]
https://github.com/IntelLabs/open-omics-alphafold/blob/8475c78cfbddc64f66c12f3bdadc87a67ca9625f/alphafold_pytorch_jit/net.py#L111

I cannot find subnets_multimer in this repo.

**Comment by intelyoungway** [comment]
https://github.com/IntelLabs/open-omics-alphafold/blob/multimer/alphafold_pytorch_jit/subnets_multimer.py

**Comment by narendrachaudhary51** [comment]
We have added multimer support into the main branch now.
