### ISSUE TITLE
cant use model_3 and many other models

### ISSUE THREAD

**Issue by dailypartita** [IntelLabs/open-omics-alphafold#7]
(base) root@f79aaa9343bd:/open-omics-alphafold# bash online_inference_baremetal.sh /opt/conda ${PWD} /afdb/AlphaFold2_DB_2023-11-23 /data/input /data/output model_3 30
bf16 variable:  True
/opt/conda/lib/python3.9/site-packages/absl/flags/_validators.py:254: UserWarning: Flag --preset has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
  mark_flag_as_required(flag_name, flag_values)
### [INFO] use 30 CPU cores
I0223 12:01:01.799637 140263135551424 run_modelinfer_pytorch_jit.py:245] Using random seed 5582232524994481130 for the data pipeline
######### /data/output/test/intermediates
/afdb/AlphaFold2_DB_2023-11-23/params/params_model_3/alphafold/alphafold_iteration/structure_module
I0223 12:01:02.183295 140263135551424 xla_bridge.py:440] Unable to initialize backend 'cuda': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
I0223 12:01:02.183439 140263135551424 xla_bridge.py:440] Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
I0223 12:01:02.184394 140263135551424 xla_bridge.py:440] Unable to initialize backend 'tpu': INVALID_ARGUMENT: TpuPlatform is not available.
I0223 12:01:02.184514 140263135551424 xla_bridge.py:440] Unable to initialize backend 'plugin': xla_extension has no attributes named get_plugin_device_client. Compile TensorFlow with //tensorflow/compiler/xla/python:enable_plugin_device set to true (defaults to false) to enable this.
W0223 12:01:02.184592 140263135551424 xla_bridge.py:448] No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
### [INFO] build evoformer network
Traceback (most recent call last):
  File "/open-omics-alphafold/run_modelinfer_pytorch_jit.py", line 274, in <module>
    app.run(main)
  File "/opt/conda/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/opt/conda/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/open-omics-alphafold/run_modelinfer_pytorch_jit.py", line 249, in main
    alphafold_infer(
  File "/open-omics-alphafold/run_modelinfer_pytorch_jit.py", line 161, in alphafold_infer
    model_runner = model.RunModel(
  File "/open-omics-alphafold/alphafold_pytorch_jit/net.py", line 123, in __init__
    self.model = subnets.AlphaFold(
  File "/open-omics-alphafold/alphafold_pytorch_jit/subnets.py", line 263, in __init__
    af2iter_params = filtered_pth_params(af2iter_params, self.impl)
  File "/open-omics-alphafold/alphafold_pytorch_jit/weight_io.py", line 107, in filtered_pth_params
    res[name] = pth_params[name]
KeyError: 'evoformer.template_embedding.single_template_embedding.embedding2d.weight'

**Comment by narendrachaudhary51** [comment]
Please use the latest commit. This problem was resolved some time ago in a commit.
